import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { $ } from 'bun';
import type { RepoConfig } from './config';
import type { TestRoadmap } from './roadmap-generator';

const CACHE_DIR = '.agents/qa-scan/cache';

export function getCachePath(repo: RepoConfig, workspace: string): string {
  return join(workspace, CACHE_DIR, repo.key);
}

export async function getGitHead(repoPath: string): Promise<string | null> {
  try {
    const result = await $`git -C ${repoPath} rev-parse HEAD`.text();
    return result.trim();
  } catch {
    return null;
  }
}

export function getCachedCommit(repo: RepoConfig, workspace: string): string | null {
  const commitFile = join(getCachePath(repo, workspace), '.analyzed-commit');
  if (!existsSync(commitFile)) return null;
  return readFileSync(commitFile, 'utf-8').trim();
}

export function isCacheValid(repo: RepoConfig, workspace: string): boolean {
  const cachedCommit = getCachedCommit(repo, workspace);
  if (!cachedCommit) return false;

  const repoPath = join(workspace, repo.path);
  try {
    const result = Bun.spawnSync(['git', '-C', repoPath, 'rev-parse', 'HEAD']);
    const currentCommit = new TextDecoder().decode(result.stdout).trim();
    return cachedCommit === currentCommit;
  } catch {
    return false;
  }
}

export function loadRoadmap(repo: RepoConfig, workspace: string): TestRoadmap | null {
  const roadmapPath = join(getCachePath(repo, workspace), 'test-roadmap.json');
  if (!existsSync(roadmapPath)) return null;
  return JSON.parse(readFileSync(roadmapPath, 'utf-8'));
}

export function writeRoadmap(repo: RepoConfig, roadmap: TestRoadmap, workspace: string): void {
  const cachePath = getCachePath(repo, workspace);
  mkdirSync(cachePath, { recursive: true });

  writeFileSync(join(cachePath, 'test-roadmap.json'), JSON.stringify(roadmap, null, 2));
  writeFileSync(join(cachePath, '.analyzed-commit'), roadmap.commit);

  if (roadmap.test_environment?.setup_commands?.length) {
    const script = ['#!/bin/bash', '# Auto-generated by qa-scan analyze', ...roadmap.test_environment.setup_commands].join('\n');
    writeFileSync(join(cachePath, 'setup-script.sh'), script);
  }
}
